apiVersion: v1                  # Kubernetes core API group
kind: ConfigMap                 # Resource type → used to store configuration data

metadata:
  name: prometheus-config       # Name of the ConfigMap (used later in Deployment)
  namespace: monitoring         # Stored inside "monitoring" namespace (logical grouping)

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'flask-app'
        metrics_path: /metrics
        static_configs:
          - targets: ['34.133.227.191:5000']

